#!/bin/sh

LOGDIR=./log
PIDFILE=./log/pb
ACCESS_LOG=$LOGDIR/access.log
ERROR_LOG=$LOGDIR/error.log

port=5000
app='./bin/pb'

start() {
    if [ -f $PIDFILE ]; then
        echo "Process already running with pid "`cat $PIDFILE`
        ps aux | grep $app | grep -v "grep $app"
        return 1
    else
        mkdir -p $LOGDIR
        nohup $app -p $port 1> $ACCESS_LOG 2> $ERROR_LOG &
        RETVAL=$?
        pid=$!
        echo $pid > $PIDFILE
        return $RETVAL
    fi
}

stop() {
    if [ -f $PIDFILE ]; then
        kill -9 `cat $PIDFILE`
        rm -f $PIDFILE
        return $?
    else
        echo "Process is dead"
        return 2
    fi
}

restart() {
    stop
    start
}

case $1 in
    start)
        start
        exit $?
        ;;
    stop)
        stop
        exit $?
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage $0 {start|stop|restart}"
esac

exit 0
