#!/bin/sh

LOGDIR=./log
PIDFILE=./log/pb
ACCESS_LOG=$LOGDIR/access.log
ERROR_LOG=$LOGDIR/error.log

port=5000
app='./bin/pb'

start() {
    mkdir -p $LOGDIR
    nohup $app -p $port 1> $ACCESS_LOG 2> $ERROR_LOG &
    pid=$!
    echo $pid > $PIDFILE
    return $?
}

stop() {
    kill -9 `cat $PIDFILE`
    return $?
}

restart() {
    stop
    start
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage $0 {start|stop|restart}"
esac

exit 0
